version: '3'
services:
  api:
    build:
      context: ./api
    image: todolist-api
    env_file: config.env
    volumes:
      - ./api:/usr/src/api
    ports:
      - 3000:3000
    links:
      - db:db
    depends_on:
      - db
  client:
    build:
      context: ./client
    image: todolist-client
    env_file: config.env
    volumes:
      - ./client:/usr/src/client
    ports:
      - 4000:3000
    links:
      - api:api
  db:
    image: postgres:9.6.3
    env_file: config.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5431:5432
